Try and workaround pytube not able to safe file to disk
UnicodeEncodeError: 'latin-1' codec can't encode character

Seems that pytube.helpers.safe_filename doesn't cover all cases.
One example video title that likely caused this fail:

   Os Tincoãs - Deixa A Gira Girar